steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.udap.ca:$TAG_NAME', '--file', './Dockerfile', '.' ]

# See:: https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.udap.ca:$TAG_NAME']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
  'run', 'deploy', 'fhirlabs-udap-ca', 
  '--region', 'us-west1', 
  '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.udap.ca:$TAG_NAME', 
  '--max-instances', '1', 
  '--concurrency', '5',
  '--set-env-vars', 'GCLOUD_PROJECT=true,GCPDeploy=true',
  '--add-cloudsql-instances', 'udap-idp:us-west1:udap-idp-sqlexpress', 
  '--vpc-connector', 'udap-idp-conect-us-west1',
  '--vpc-egress', 'private-ranges-only',
  '--ingress', 'internal-and-cloud-load-balancing',
  '--set-secrets', '/secret/udap_ca_appsettings=udap_ca_appsettings:latest'  
]

images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.udap.ca:$TAG_NAME'