CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'udap') THEN
        CREATE SCHEMA udap;
    END IF;
END $EF$;

CREATE TABLE udap.api_resources (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enabled boolean NOT NULL,
    name character varying(200) NOT NULL,
    display_name character varying(200),
    description character varying(1000),
    allowed_access_token_signing_algorithms character varying(100),
    show_in_discovery_document boolean NOT NULL,
    require_resource_indicator boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone,
    last_accessed timestamp with time zone,
    non_editable boolean NOT NULL,
    CONSTRAINT pk_api_resources PRIMARY KEY (id)
);

CREATE TABLE udap.api_scopes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enabled boolean NOT NULL,
    name character varying(200) NOT NULL,
    display_name character varying(200),
    description character varying(1000),
    required boolean NOT NULL,
    emphasize boolean NOT NULL,
    show_in_discovery_document boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone,
    last_accessed timestamp with time zone,
    non_editable boolean NOT NULL,
    CONSTRAINT pk_api_scopes PRIMARY KEY (id)
);

CREATE TABLE udap.clients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enabled boolean NOT NULL,
    client_id character varying(200) NOT NULL,
    protocol_type character varying(200) NOT NULL,
    require_client_secret boolean NOT NULL,
    client_name character varying(200),
    description character varying(1000),
    client_uri character varying(2000),
    logo_uri character varying(2000),
    require_consent boolean NOT NULL,
    allow_remember_consent boolean NOT NULL,
    always_include_user_claims_in_id_token boolean NOT NULL,
    require_pkce boolean NOT NULL,
    allow_plain_text_pkce boolean NOT NULL,
    require_request_object boolean NOT NULL,
    allow_access_tokens_via_browser boolean NOT NULL,
    require_dpo_p boolean NOT NULL,
    dpo_pvalidation_mode integer NOT NULL,
    dpo_pclock_skew interval NOT NULL,
    front_channel_logout_uri character varying(2000),
    front_channel_logout_session_required boolean NOT NULL,
    back_channel_logout_uri character varying(2000),
    back_channel_logout_session_required boolean NOT NULL,
    allow_offline_access boolean NOT NULL,
    identity_token_lifetime integer NOT NULL,
    allowed_identity_token_signing_algorithms character varying(100),
    access_token_lifetime integer NOT NULL,
    authorization_code_lifetime integer NOT NULL,
    consent_lifetime integer,
    absolute_refresh_token_lifetime integer NOT NULL,
    sliding_refresh_token_lifetime integer NOT NULL,
    refresh_token_usage integer NOT NULL,
    update_access_token_claims_on_refresh boolean NOT NULL,
    refresh_token_expiration integer NOT NULL,
    access_token_type integer NOT NULL,
    enable_local_login boolean NOT NULL,
    include_jwt_id boolean NOT NULL,
    always_send_client_claims boolean NOT NULL,
    client_claims_prefix character varying(200),
    pair_wise_subject_salt character varying(200),
    initiate_login_uri character varying(2000),
    user_sso_lifetime integer,
    user_code_type character varying(100),
    device_code_lifetime integer NOT NULL,
    ciba_lifetime integer,
    polling_interval integer,
    coordinate_lifetime_with_user_session boolean,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone,
    last_accessed timestamp with time zone,
    non_editable boolean NOT NULL,
    pushed_authorization_lifetime integer,
    require_pushed_authorization boolean NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE udap.identity_providers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    scheme character varying(200) NOT NULL,
    display_name character varying(200),
    enabled boolean NOT NULL,
    type character varying(20) NOT NULL,
    properties text,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone,
    last_accessed timestamp with time zone,
    non_editable boolean NOT NULL,
    CONSTRAINT pk_identity_providers PRIMARY KEY (id)
);

CREATE TABLE udap.identity_resources (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enabled boolean NOT NULL,
    name character varying(200) NOT NULL,
    display_name character varying(200),
    description character varying(1000),
    required boolean NOT NULL,
    emphasize boolean NOT NULL,
    show_in_discovery_document boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone,
    non_editable boolean NOT NULL,
    CONSTRAINT pk_identity_resources PRIMARY KEY (id)
);

CREATE TABLE udap.api_resource_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    api_resource_id integer NOT NULL,
    type character varying(200) NOT NULL,
    CONSTRAINT pk_api_resource_claims PRIMARY KEY (id),
    CONSTRAINT fk_api_resource_claims_api_resources_api_resource_id FOREIGN KEY (api_resource_id) REFERENCES udap.api_resources (id) ON DELETE CASCADE
);

CREATE TABLE udap.api_resource_properties (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    api_resource_id integer NOT NULL,
    key character varying(250) NOT NULL,
    value character varying(2000) NOT NULL,
    CONSTRAINT pk_api_resource_properties PRIMARY KEY (id),
    CONSTRAINT fk_api_resource_properties_api_resources_api_resource_id FOREIGN KEY (api_resource_id) REFERENCES udap.api_resources (id) ON DELETE CASCADE
);

CREATE TABLE udap.api_resource_scopes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    scope character varying(200) NOT NULL,
    api_resource_id integer NOT NULL,
    CONSTRAINT pk_api_resource_scopes PRIMARY KEY (id),
    CONSTRAINT fk_api_resource_scopes_api_resources_api_resource_id FOREIGN KEY (api_resource_id) REFERENCES udap.api_resources (id) ON DELETE CASCADE
);

CREATE TABLE udap.api_resource_secrets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    api_resource_id integer NOT NULL,
    description character varying(1000),
    value character varying(4000) NOT NULL,
    expiration timestamp with time zone,
    type character varying(250) NOT NULL,
    created timestamp with time zone NOT NULL,
    CONSTRAINT pk_api_resource_secrets PRIMARY KEY (id),
    CONSTRAINT fk_api_resource_secrets_api_resources_api_resource_id FOREIGN KEY (api_resource_id) REFERENCES udap.api_resources (id) ON DELETE CASCADE
);

CREATE TABLE udap.api_scope_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    scope_id integer NOT NULL,
    type character varying(200) NOT NULL,
    CONSTRAINT pk_api_scope_claims PRIMARY KEY (id),
    CONSTRAINT fk_api_scope_claims_api_scopes_scope_id FOREIGN KEY (scope_id) REFERENCES udap.api_scopes (id) ON DELETE CASCADE
);

CREATE TABLE udap.api_scope_properties (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    scope_id integer NOT NULL,
    key character varying(250) NOT NULL,
    value character varying(2000) NOT NULL,
    CONSTRAINT pk_api_scope_properties PRIMARY KEY (id),
    CONSTRAINT fk_api_scope_properties_api_scopes_scope_id FOREIGN KEY (scope_id) REFERENCES udap.api_scopes (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    type character varying(250) NOT NULL,
    value character varying(250) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_claims PRIMARY KEY (id),
    CONSTRAINT fk_client_claims_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_cors_origins (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    origin character varying(150) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_cors_origins PRIMARY KEY (id),
    CONSTRAINT fk_client_cors_origins_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_grant_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    grant_type character varying(250) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_grant_types PRIMARY KEY (id),
    CONSTRAINT fk_client_grant_types_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_id_prestrictions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    provider character varying(200) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_id_prestrictions PRIMARY KEY (id),
    CONSTRAINT fk_client_id_prestrictions_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_post_logout_redirect_uris (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    post_logout_redirect_uri character varying(400) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_post_logout_redirect_uris PRIMARY KEY (id),
    CONSTRAINT fk_client_post_logout_redirect_uris_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_properties (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    key character varying(250) NOT NULL,
    value character varying(2000) NOT NULL,
    CONSTRAINT pk_client_properties PRIMARY KEY (id),
    CONSTRAINT fk_client_properties_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_redirect_uris (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    redirect_uri character varying(400) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_redirect_uris PRIMARY KEY (id),
    CONSTRAINT fk_client_redirect_uris_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_scopes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    scope character varying(200) NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT pk_client_scopes PRIMARY KEY (id),
    CONSTRAINT fk_client_scopes_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.client_secrets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    description character varying(2000),
    value character varying(4000) NOT NULL,
    expiration timestamp with time zone,
    type character varying(250) NOT NULL,
    created timestamp with time zone NOT NULL,
    CONSTRAINT pk_client_secrets PRIMARY KEY (id),
    CONSTRAINT fk_client_secrets_clients_client_id FOREIGN KEY (client_id) REFERENCES udap.clients (id) ON DELETE CASCADE
);

CREATE TABLE udap.identity_resource_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    identity_resource_id integer NOT NULL,
    type character varying(200) NOT NULL,
    CONSTRAINT pk_identity_resource_claims PRIMARY KEY (id),
    CONSTRAINT "fk_identity_resource_claims_identity_resources_identity_resour~" FOREIGN KEY (identity_resource_id) REFERENCES udap.identity_resources (id) ON DELETE CASCADE
);

CREATE TABLE udap.identity_resource_properties (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    identity_resource_id integer NOT NULL,
    key character varying(250) NOT NULL,
    value character varying(2000) NOT NULL,
    CONSTRAINT pk_identity_resource_properties PRIMARY KEY (id),
    CONSTRAINT "fk_identity_resource_properties_identity_resources_identity_re~" FOREIGN KEY (identity_resource_id) REFERENCES udap.identity_resources (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_api_resource_claims_api_resource_id_type ON udap.api_resource_claims (api_resource_id, type);

CREATE UNIQUE INDEX ix_api_resource_properties_api_resource_id_key ON udap.api_resource_properties (api_resource_id, key);

CREATE UNIQUE INDEX ix_api_resource_scopes_api_resource_id_scope ON udap.api_resource_scopes (api_resource_id, scope);

CREATE INDEX ix_api_resource_secrets_api_resource_id ON udap.api_resource_secrets (api_resource_id);

CREATE UNIQUE INDEX ix_api_resources_name ON udap.api_resources (name);

CREATE UNIQUE INDEX ix_api_scope_claims_scope_id_type ON udap.api_scope_claims (scope_id, type);

CREATE UNIQUE INDEX ix_api_scope_properties_scope_id_key ON udap.api_scope_properties (scope_id, key);

CREATE UNIQUE INDEX ix_api_scopes_name ON udap.api_scopes (name);

CREATE UNIQUE INDEX ix_client_claims_client_id_type_value ON udap.client_claims (client_id, type, value);

CREATE UNIQUE INDEX ix_client_cors_origins_client_id_origin ON udap.client_cors_origins (client_id, origin);

CREATE UNIQUE INDEX ix_client_grant_types_client_id_grant_type ON udap.client_grant_types (client_id, grant_type);

CREATE UNIQUE INDEX ix_client_id_prestrictions_client_id_provider ON udap.client_id_prestrictions (client_id, provider);

CREATE UNIQUE INDEX "ix_client_post_logout_redirect_uris_client_id_post_logout_redi~" ON udap.client_post_logout_redirect_uris (client_id, post_logout_redirect_uri);

CREATE UNIQUE INDEX ix_client_properties_client_id_key ON udap.client_properties (client_id, key);

CREATE UNIQUE INDEX ix_client_redirect_uris_client_id_redirect_uri ON udap.client_redirect_uris (client_id, redirect_uri);

CREATE UNIQUE INDEX ix_client_scopes_client_id_scope ON udap.client_scopes (client_id, scope);

CREATE INDEX ix_client_secrets_client_id ON udap.client_secrets (client_id);

CREATE UNIQUE INDEX ix_clients_client_id ON udap.clients (client_id);

CREATE UNIQUE INDEX ix_identity_providers_scheme ON udap.identity_providers (scheme);

CREATE UNIQUE INDEX ix_identity_resource_claims_identity_resource_id_type ON udap.identity_resource_claims (identity_resource_id, type);

CREATE UNIQUE INDEX ix_identity_resource_properties_identity_resource_id_key ON udap.identity_resource_properties (identity_resource_id, key);

CREATE UNIQUE INDEX ix_identity_resources_name ON udap.identity_resources (name);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240405193308_ConfigurationDB_Initial', '8.0.3');

COMMIT;

